version: '2'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config



  rabbitmq-consumer1:
    build: rabbitmq-consumer1/
    restart: always
    network_mode: "host"
    ports:
      - 9091:9091

  rabbitmq-consumer2:
    build: rabbitmq-consumer2/
    restart: always
    network_mode: "host"
    ports:
      - 9092:9092

  rabbitmq-consumer3:
    build: rabbitmq-consumer3/
    restart: always
    network_mode: "host"
    ports:
      - 9093:9093

  rabbitmq-producer:
    build: rabbitmq-producer/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 9001:9001


